"""Regenerate docs/assumptions.md from sunrisk/config.py (the single source of truth)."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "model"))
from sunrisk import config  # noqa: E402

HEADER = """# Assumptions

<!-- Generated by model/scripts/render_assumptions.py from model/sunrisk/config.py. Do not edit by hand. -->

Every number the model uses that is not a physical definition. **Low** confidence values are
placeholders that must be revisited with our own data or a proper literature review before we
claim accuracy. Citations were written from memory during setup; check each one against the
original paper before quoting it in the report.

| Name | Value | Unit | Confidence | Source / note |
|---|---:|---|---|---|
"""


def render() -> str:
    rows = []
    for name, a in config.all_assumptions().items():
        note = a.source + (f" {a.note}" if a.note else "")
        rows.append(f"| `{name}` | {a.value:g} | {a.unit} | {a.confidence} | {note} |")
    return HEADER + "\n".join(rows) + "\n"


if __name__ == "__main__":
    out = ROOT / "docs" / "assumptions.md"
    out.write_text(render())
    print(f"wrote {out}")
